### ISSUE TITLE
Prototype Documentation

### ISSUE THREAD

**Issue by robinsonkal** [Berea-CS-Courses/capstone-project-robinsonkal#11]
__One sentence overview of your submission__
This is the documentation to the D4 prototype 

__I would like feedback on ...__

**Comment by alfarozavalae** [comment]
This issue seems to be incomplete. If you no longer needed it feel free to delete it or close it.

**Comment by alfarozavalae** [comment]
please close this issue. There is no commits or pull requests linked here so I am assuming you do not need this issue.
