### ISSUE TITLE
Issue for weekly update 2

### ISSUE THREAD

**Issue by robinsonkal** [Berea-CS-Courses/capstone-project-robinsonkal#15]
__One sentence overview of your submission__
 This is the issue for the 2nd weekly update

__I would like feedback on ...__ 
Any thoughts on methodologies for text analysis would be appreciated. Or anything else really.

**Comment by alfarozavalae** [comment]
Please specify what this issue is for by adding the #[issuenumber] in the description (i.e. "#17 adding new stop words") that way we can comment it here. You're no longer required to do an issue for the weekly updates.

**Comment by alfarozavalae** [comment]
If you do not have any issue related to the weekly update, feel free to close this issue.

**Comment by alfarozavalae** [comment]
please close this issue. There is no commits or pull requests linked here so I am assuming you do not need this issue.
