### ISSUE TITLE
Issue for weekly update 3

### ISSUE THREAD

**Issue by robinsonkal** [Berea-CS-Courses/capstone-project-robinsonkal#17]
__One sentence overview of your submission__
This is the issue for my weekly update 3 documentation.

__I would like feedback on ...__ 
Whatever comes to mind.

**Comment by jazzij** [comment]
Nothing's linked to this, so not sure what this issue is for... What code updates are you submitting here? To link a commit or a pull request to an issue, add the #[issuenumber] in the description (i.e. "#17 adding new stop words")

**Comment by alfarozavalae** [comment]
please close this issue. There is no commits or pull requests linked here so I am assuming you do not need this issue.
