### ISSUE TITLE
[Deliverable 1]

### ISSUE THREAD

**Issue by robinsonkal** [Berea-CS-Courses/capstone-project-robinsonkal#2]
__One sentence overview of your submission__
 This document outlines my project which aims to identify coded racist language online using text analysis.

__I would like feedback on ...__ 
I'm unsure if I did the requirements section right, especially the non functional section, so I could use a bit of specification on what is needed.

**Comment by belainehi** [comment]
Great job clearly defining the purpose and scope of this project. The functional and non-functional requirements are also clear. What is meant by making the software transferable to web application? The back end hosting of your data is also part of a non-functional requirement. Great breakdown overall.

**Comment by Bryar-Frank** [comment]
After reviewing the feedback on this Issue, you may close it :)
